version: "3"

services:
  client_web:
    image: node:lts
    working_dir: /usr/src/client_web
    volumes:
      - ./:/usr/src/client_web
    command: yarn ng serve --host 0.0.0.0
    ports:
      - 4200:4200
